[tool.poetry]
name = "largebot"
version = "0.2.0"
description = ""
authors = ["welocalize <aie-devel@welocalize.com>"]

[tool.poetry.dependencies]
python = "^3.8"
welo365 = "^0.4.12"
O365 = "^2.0.11"
pandas = "^1.1.4"
xlrd = "^1.2.0"
openpyxl = "^3.0.5"
typer = "^0.3.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
mypy = "^0.790"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "mypypi"
url = "http://10.100.1.89:8081/simple/"
secondary = true

[tool.poetry.scripts]
largebot = "largebot.main:app"