[tool.poetry]
name = "largebot"
version = "4.0.5"
description = ""
authors = ["welocalize <aie-devel@welocalize.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pydantic = "^1.7.2"
welo365 = "^1.0.17"
O365 = "^2.0.11"
pandas = "^1.1.4"
xlrd = "^1.2.0"
openpyxl = "^3.0.5"
typer = "^0.3.2"
pymsteams = "^0.1.14"
tabulate = "^0.8.7"
Faker = "^4.17.1"
arrow = "^0.17.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
mypy = "^0.790"
ipython = "^7.19.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "mypypi"
url = "http://10.100.1.89:8081/simple/"
secondary = true

[tool.poetry.scripts]
largebot = "largebot.main:app"
